/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function vnRecognizeTextRequest(w: number, h: number, b: Buffer, t?: number | undefined | null): Array<string>
export type ocr = Ocr
export class Ocr {
  static process(b: Buffer, t?: number | undefined | null): Array<string>
}
